### ISSUE TITLE
Div scrolling doesn't work in Firefox

### ISSUE THREAD

**Issue by michaelsproul** [kennib/below-the-line#1]
Not exactly sure what's going on but the `overflow-y: scroll` CSS properties generated by Elm aren't being correctly interpreted by Firefox (v47.0, Mac OS X 10.11.5). The area on the right showing the full list of candidates is cut off, rendering the site completely unusable.

I tried adding `overflow-y: scroll` to a few more individual elements, without success. What did work was adding a global rule for `divs` to overflow vertically, as in:

``` css
div {
  overflow-y: scroll
}
```

which is a massive hack...

**Comment by kennib** [comment]
Thanks for posting the issue. I've made a fix in f79d67cf6e0f58222de2d7a145d0233d27bb4264.

The main problem was that Firefox didn't make the height of the scrollable areas fit the screen.
It's a little bit of a hack since it doesn't fit the areas to (the size of the screen - the top nav bar) but it's better than being completely unusable.

**Comment by michaelsproul** [comment]
Nice!
